# -*- mode: ruby -*-
# vi: set ft=ruby :
#

# Select the FIRST-priority interface on the dedicated server to bridge.
VM_INTERFACES = %x( VBoxManage list bridgedifs | grep ^Name ).gsub(/Name:\s+/, '').split("\n")

# Extra public/bridged ethernet interface for guest system
VBOX_NETIF = VM_INTERFACES[0]

# Fixed Mac address for public/bridge ethernet interface
VBOX_MAC = "0A0C8900FFFF"

# VBOX Name
PROJECT_NAME = File.basename(Dir.getwd)

Vagrant.configure("2") do |config|
  config.vm.box = "ailispaw/barge"
  config.vm.hostname = "#{PROJECT_NAME}-1"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
	bridge: VBOX_NETIF,
	mac: VBOX_MAC
  config.vm.provision "shell", inline: "docker run --name aaa --net=host -d yagamy/node-web-app2"
end
