#!/bin/bash

function run {
	echo "$@"
	${BASH} -c "$@"
}

function entry {
	local TMP=$(pwd)
	cd $(dirname $0)
	local DIR=$(pwd)
	local IMAGE=$(basename ${DIR})
	cd ${TMP}
	local USERNAME=$(whoami)
	local PORT=$(cat ${DIR}/Dockerfile | grep "^EXPOSE" | head -n1  | awk '{print $2}' | sed 's/\ //g')
	run "docker run --name ${IMAGE}-$(date '+%s') -p ${PORT}:${PORT} -d ${USERNAME}/${IMAGE}"
}

entry $@
