#!/bin/bash

function run {
	echo "$@"
	${BASH} -c "$@"
}

function entry {
	local TMP=$(pwd)
	cd $(dirname $0)
	local IMAGE=$(basename $(pwd))
	cd ${TMP}
	local USERNAME=$(whoami)
	echo "start ..." &&
		run "docker build -t ${USERNAME}/${IMAGE} ." &&
		run "docker images" &&
		run "docker history ${USERNAME}/${IMAGE}"
}

entry $@
