# -*- mode: ruby -*-
# vi: set ft=ruby :
#

# Select the FIRST-priority interface on the dedicated server to bridge.
VM_INTERFACES = %x( VBoxManage list bridgedifs | grep ^Name ).gsub(/Name:\s+/, '').split("\n")

# Extra public/bridged ethernet interface for guest system
VBOX_NETIF = VM_INTERFACES[0]

# Fixed Mac address for public/bridge ethernet interface
VBOX_MAC = "0A0C8900FFFF"

$script = <<SCRIPT
docker run --name aaa --net=host -d yagamy/node-web-app1
echo please run this command on MacOS:
echo   http http://$(ifconfig eth1 | grep "inet addr:" | awk '{print $2}' | awk -F':' '{print $2}'):8080
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ailispaw/barge"
  config.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
	bridge: VBOX_NETIF,
	mac: VBOX_MAC
  config.vm.provision "shell", inline: $script
end
