#!/bin/bash

function run {
	echo "$@"
	${BASH} -c "$@"
}

function entry {
	local TMP=$(pwd)
	cd $(dirname $0)
	local IMAGE=$(basename $(pwd))
	cd ${TMP}
	local USERNAME=$(whoami)
	run "docker push ${USERNAME}/${IMAGE}"
}

entry $@
